CHECKLIST_ITEMS = [
    {
        "category": "邮箱",
        "title": "开启两步验证（2FA）",
        "description": "在邮箱设置里打开短信或验证器 App 的二次验证。",
        "priority": "高",
        "sort_order": 1,
    },
    {
        "category": "邮箱",
        "title": "使用独立强密码",
        "description": "邮箱密码不要和其他网站相同，建议用密码管理器生成。",
        "priority": "高",
        "sort_order": 2,
    },
    {
        "category": "邮箱",
        "title": "检查恢复邮箱和手机",
        "description": "确认备用邮箱、手机号是你本人在用的，不是很久以前的号码。",
        "priority": "高",
        "sort_order": 3,
    },
    {
        "category": "邮箱",
        "title": "检查登录设备和异常登录",
        "description": "在安全设置里查看最近登录地点，退出不认识的设备。",
        "priority": "中",
        "sort_order": 4,
    },
    {
        "category": "邮箱",
        "title": "保存两步验证备份码",
        "description": "把备份码写在纸上或离线保存，手机丢了还能登录。",
        "priority": "中",
        "sort_order": 5,
    },
    {
        "category": "银行/支付",
        "title": "开启交易提醒",
        "description": "开通短信或 App 推送，每一笔消费都通知你。",
        "priority": "高",
        "sort_order": 6,
    },
    {
        "category": "银行/支付",
        "title": "关闭小额免密支付",
        "description": "在微信、支付宝或银行卡设置里关闭免密，降低盗刷风险。",
        "priority": "高",
        "sort_order": 7,
    },
    {
        "category": "银行/支付",
        "title": "检查绑定设备和银行卡",
        "description": "核对绑定的手机、手表、快捷支付卡片，解绑不用的。",
        "priority": "高",
        "sort_order": 8,
    },
    {
        "category": "银行/支付",
        "title": "设置转账和支付限额",
        "description": "日限额设低一点，被骗时损失会小很多。",
        "priority": "中",
        "sort_order": 9,
    },
    {
        "category": "银行/支付",
        "title": "只用官方 App 办理业务",
        "description": "不要点短信链接下载“银行 App”，去应用商店搜索官方名称。",
        "priority": "高",
        "sort_order": 10,
    },
    {
        "category": "社交",
        "title": "开启两步验证",
        "description": "微信、QQ、微博、Instagram 等尽量打开二次验证。",
        "priority": "高",
        "sort_order": 11,
    },
    {
        "category": "社交",
        "title": "关闭手机号或邮箱被搜索",
        "description": "避免陌生人用你的号码找到账号并诈骗好友。",
        "priority": "中",
        "sort_order": 12,
    },
    {
        "category": "社交",
        "title": "检查第三方应用授权",
        "description": "取消很久不用、不认识的登录授权。",
        "priority": "中",
        "sort_order": 13,
    },
    {
        "category": "社交",
        "title": "检查登录设备",
        "description": "退出网吧、旧手机、不认识的电脑会话。",
        "priority": "高",
        "sort_order": 14,
    },
    {
        "category": "社交",
        "title": "设置强密码且不复用",
        "description": "社交账号被盗后，常用来骗你的家人朋友。",
        "priority": "高",
        "sort_order": 15,
    },
    {
        "category": "学校/工作",
        "title": "开启学校或公司邮箱 2FA",
        "description": "教育邮箱、企业邮箱被盗会导致作业、工资、签证信息泄露。",
        "priority": "高",
        "sort_order": 16,
    },
    {
        "category": "学校/工作",
        "title": "检查邮箱自动转发规则",
        "description": "黑客常偷偷加转发，邮件会被悄悄寄走。",
        "priority": "高",
        "sort_order": 17,
    },
    {
        "category": "学校/工作",
        "title": "工作账号使用独立密码",
        "description": "不要和工作邮箱用同一个密码登录购物网站。",
        "priority": "高",
        "sort_order": 18,
    },
    {
        "category": "学校/工作",
        "title": "核对找回方式和紧急联系人",
        "description": "确认恢复邮箱不是过期的个人邮箱。",
        "priority": "中",
        "sort_order": 19,
    },
    {
        "category": "学校/工作",
        "title": "保存单点登录备份码",
        "description": "学校门户、VPN、办公套件的备份码要离线保存。",
        "priority": "中",
        "sort_order": 20,
    },
    {
        "category": "云盘/照片",
        "title": "云盘开启两步验证",
        "description": "网盘里常有身份证、合同、家庭照片。",
        "priority": "高",
        "sort_order": 21,
    },
    {
        "category": "云盘/照片",
        "title": "检查共享链接",
        "description": "把“任何人可查看”的旧链接关掉或改成指定人。",
        "priority": "高",
        "sort_order": 22,
    },
    {
        "category": "云盘/照片",
        "title": "关闭不必要的公开链接",
        "description": "相册、简历文件夹不要设为公开。",
        "priority": "中",
        "sort_order": 23,
    },
    {
        "category": "云盘/照片",
        "title": "检查第三方应用授权",
        "description": "取消不知名修图、打印、简历网站的云盘权限。",
        "priority": "中",
        "sort_order": 24,
    },
    {
        "category": "云盘/照片",
        "title": "备份重要文件到第二处",
        "description": "U 盘或另一家云盘再放一份，账号被封也不至于全丢。",
        "priority": "中",
        "sort_order": 25,
    },
]
